exploit_index:
    path:     /
    defaults: { _controller: "AppBundle:Exploit:index"}
    methods:  GET

exploit_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Exploit:show" }
    methods:  GET

exploit_new:
    path:     /new
    defaults: { _controller: "AppBundle:Exploit:new" }
    methods:  [GET, POST]

exploit_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Exploit:edit" }
    methods:  [GET, POST]

exploit_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Exploit:delete" }
    methods:  DELETE

exploit_vote:
    path:     /{id}/vote
    defaults: { _controller: "AppBundle:Exploit:vote" }
    methods:  [GET, POST]

exploit_domaine:
    path:     /{id}/domaine
    defaults: { _controller: AppBundle:Exploit:domaine , format: html}
    methods:  GET
    requirements:
        id: \d+
        format: html|xml

form_galerie:
    path:     /galerie
    defaults: { _controller: "AppBundle:Exploit:galerie" }
    methods:  [GET, POST]


form_exploitAprenant:
    path:     /exploitAprenant
    defaults: { _controller: "AppBundle:Exploit:exploitAprenant" }
    methods:  GET

impression:
    path:     /imprime
    defaults: { _controller: "AppBundle:Exploit:imprimer" }
    methods:  GET

form_comment:
    path:     /comment
    defaults: { _controller: "AppBundle:Exploit:comment" }
    methods:  [GET, POST]
