api_exploit_index:
    path:     /
    defaults: { _controller: "APIExploitBundle:Exploit:index"}
    methods:  GET

api_exploit_show:
    path:     /{id}/show
    defaults: { _controller: "APIExploitBundle:Exploit:show" }
    methods:  GET

api_exploit_new:
    path:     /new
    defaults: { _controller: "APIExploitBundle:Exploit:new" }
    methods:  [GET, POST]

api_exploit_edit:
    path:     /{id}/edit
    defaults: { _controller: "APIExploitBundle:Exploit:edit" }
    methods:  [GET, POST]

api_exploit_delete:
    path:     /{id}/delete
    defaults: { _controller: "APIExploitBundle:Exploit:delete" }
    methods:  DELETE

api_exploit_vote:
    path:     /{id}/vote
    defaults: { _controller: "APIExploitBundle:Exploit:vote" }
    methods:  [GET, POST]

api_exploit_domaine:
    path:     /{id}/domaine
    defaults: { _controller: "APIExploitBundle:Exploit:domaine" , format: html}
    methods:  GET
    requirements:
        id: \d+
        format: html|xml    
