services:
#    api_info.example:
#        class: API\InfoBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

     api_info.date_publication_listener:
         class: API\InfoBundle\Listener\DatePublication
         tags:
             - { name: kernel.event_listener, event: information.publie_to_true,method: onPublieATrue }
