<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApprenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApprenantRepository extends EntityRepository
{
    function getApprenant()
   {
       $em = $this->getEntityManager();
       $query = $em->createQueryBuilder()
           ->select('e')
           ->from('AppBundle:Apprenant', 'e')
           ->orderBy('e.id', 'DESC')
           ->setMaxResults(1);
       return $query->getQuery()
           ->getResult();
   }

   function apprenantsOfTuteur($id)
   {
       $queryBuilder = $this->_em->createQueryBuilder()
           ->select('ap')
           ->from('AppBundle:Apprenant', 'ap')
           ->leftJoin('ap.tuteur', 't')
           ->where('t.id = :id')
           ->setParameter('id', $id)
           ->orderBy('ap.id', 'DESC');

       return $apprenents = $queryBuilder->getQuery()
           ->getArrayResult();

   }

}
