<?php

namespace AppBundle\Repository;

/**
 * BugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BugRepository extends \Doctrine\ORM\EntityRepository
{
}
