<?php

namespace AppBundle\Repository;

/**
 * CursusApprenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursusApprenantRepository extends \Doctrine\ORM\EntityRepository
{
}
