<?php

namespace AppBundle\Repository;

/**
 * DirigeantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirigeantRepository extends \Doctrine\ORM\EntityRepository
{
}
