<?php

namespace AppBundle\Repository;

/**
 * EnseignerSecondaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignerSecondaireRepository extends \Doctrine\ORM\EntityRepository
{
}
