<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementClasseNiveauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementClasseNiveauRepository extends EntityRepository
{
    function getNiveauByEtablissementAndClasse($etablissementClasse)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('ecn', 'n')
            ->from('AppBundle:EtablissementClasseNiveau', 'ecn')
            ->join('ecn.etablissementClasse', 'ec')
            ->join('ecn.niveauEtude', 'n')
            ->andWhere('ec =:classSelect')
            ->setParameter('classSelect', $etablissementClasse)
            ->orderBy('n.libelleNiveauEtude');
        return $query->getQuery()
            ->getResult();


    }

}
