<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends EntityRepository
{

  function getAllEts() {

    $qb = $this->createQueryBuilder('e')
              ->join('e.votes','v')
              ->addSelect('v.nbreEtoiles');

    return $qb->getQuery()
              ->getResult();
  }

    public function myFindAll()
    {
        return $this->createQueryBuilder('e')
            ->getQuery()
            ->getArrayResult();
    }

//retourne les etablissements suivant des caractéristiques données
// function getEtablissementsByCaracteristiques($niveau, $statut, $categorie)
// {
//   $queryBuilder = $this->_em->createQueryBuilder()
//                             ->select('e')
//                             ->from('AppBundle:Etablissement', 'e')
//                             ->where('e.niveauEtablissement = :niveau')
//                             ->andWhere('e.statutEtablissement = :statut');
//   if ($categorie == 'Neant') {
//     $queryBuilder->andWhere('e.categorieEtablissement IS NULL')
//                   ->setParameters(array( 'statut' => $statut,
//                                          'niveau' => $niveau
//                                  ));
//   }
//   else {
//     $queryBuilder->andWhere('e.categorieEtablissement =:categorie')
//                   ->setParameters(array( 'categorie' => $categorie,
//                                           'statut' => $statut,
//                                          'niveau' => $niveau
//                                  ));
//   }
//
//
//   return $etablissementsListe = $queryBuilder->getQuery()
//                                              ->getArrayResult();
// }

function getEtablissementsByCaracteristiques($niveau, $statut)
{
  $queryBuilder = $this->_em->createQueryBuilder()
                            ->select('e')
                            ->from('AppBundle:Etablissement', 'e')
                            ->where('e.niveauEtablissement = :niveau')
                            ->andWhere('e.statutEtablissement = :statut')
                            ->andWhere('e.categorieEtablissement IS NULL')
                            ->setParameters(array( 'statut' => $statut,
                                         'niveau' => $niveau
                                 ));

  return $etablissementsListe = $queryBuilder->getQuery()
                                             ->getArrayResult();
}


}
