<?php

namespace AppBundle\Repository;

/**
 * EtablissementProfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementProfRepository extends \Doctrine\ORM\EntityRepository
{
}
