<?php

namespace AppBundle\Repository;

/**
 * EtablissementFiliereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementFiliereRepository extends \Doctrine\ORM\EntityRepository
{
}
