<?php

namespace AppBundle\Repository;

/**
 * EtablissementDirigeantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementDirigeantRepository extends \Doctrine\ORM\EntityRepository
{
}
