<?php

namespace AppBundle\Repository;

/**
 * EtablissementApprenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementApprenantRepository extends \Doctrine\ORM\EntityRepository
{
}
