<?php

namespace AppBundle\Repository;

/**
 * EtatApprenantSecondaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatApprenantSecondaireRepository extends \Doctrine\ORM\EntityRepository
{
}
