<?php

namespace AppBundle\Repository;

/**
 * FondateurOuDirecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FondateurOuDirecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
