<?php

namespace AppBundle\Repository;

/**
 * MatiereSecondaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereSecondaireRepository extends \Doctrine\ORM\EntityRepository
{
}
