<?php

namespace AppBundle\Repository;

/**
 * MoyennePeriodiqueApprenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyennePeriodiqueApprenantRepository extends \Doctrine\ORM\EntityRepository
{
}
