<?php

namespace AppBundle\Repository;

/**
 * NoteSecondaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteSecondaireRepository extends \Doctrine\ORM\EntityRepository
{
}
