<?php

namespace AppBundle\Repository;

/**
 * ProgrammeCoursSecondaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeCoursSecondaireRepository extends \Doctrine\ORM\EntityRepository
{
}
