<?php

namespace AppBundle\Repository;

/**
 * ProgrammeCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
