<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SousClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousClasseRepository extends EntityRepository
{
    public function getSousClassesOfFiliere($ets, $classe)
    {
    }
}
