<?php

namespace AppBundle\Repository;

/**
 * StatPeriodiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatPeriodiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
