<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuteurRepository extends EntityRepository
{

    function getLastTuteur()
   {
       $em = $this->getEntityManager();
       $query = $em->createQueryBuilder()
           ->select('t')
           ->from('AppBundle:Tuteur', 't')
           ->orderBy('t.id', 'DESC')
           ->setMaxResults(1);
       return $query->getQuery()
           ->getResult();


   }
}
