<?php

namespace AppBundle\Repository;

/**
 * UploadedFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadedFileRepository extends \Doctrine\ORM\EntityRepository
{
}
