AppBundle\Entity\CommentaireExploit:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentaireExploitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contenu:
            type: string
            length: 255
    manyToOne:
        exploitApprenant:
            targetEntity: ExploitApprenant
            inversedBy:  commentairesExploit
            joinColumn:
                exploit_apprenant_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
