AppBundle\Entity\ExploitApprenant:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ExploitApprenantRepository
    id:
      id:
        type: integer
        id: true
        generator:
            strategy: AUTO
    manyToOne:
        exploit:
            targetEntity: Exploit
            inversedBy:  exploitApprenants
            joinColumn:
                exploit_id:
                    referencedColumnName: id
                    persist: cascade
        apprenant:
            targetEntity: Apprenant
            inversedBy: exploitApprenants
            joinColumn:
                apprenant_id:
                    referencedColumnName: id
                    persist: cascade
    oneToMany:
      commentairesExploit:
        targetEntity: CommentaireExploit
        mappedBy: exploitApprenant
    lifecycleCallbacks: {  }
