AppBundle\Entity\Exploit:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ExploitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: '100'
        description:
            type: text
        datePublication:
            type: datetime
            column: date_publication
        point:
            type: integer
        niveau:
            type: array
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
        typeAuteur:
            type: array
            column: type_auteur
    manyToOne:
         sousDomaine:
            targetEntity: SousDomaine
            inversedBy: exploits
    oneToMany:
          exploitFichiers:
            targetEntity: Fichier
            mappedBy: exploit
            cascade: ['persist']
          exploitApprenants:
            targetEntity: ExploitApprenant
            mappedBy: exploit
            cascade: ['persist']
    lifecycleCallbacks: {  }
