AppBundle\Entity\Expose:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ExposeRepository
    fields:
        matiere:
            type: string
            length: 255
        typeExpose:
            type: string
            length: 255
            column: type_expose
    lifecycleCallbacks: {  }
