<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbwk242\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbwk242/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXbwk242.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXbwk242\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXbwk242\appDevDebugProjectContainer();
